const API_BASE_URL_DEVELOPEMENT = 'https://localhost:44354';
const API_BASE_URL_PRODUCTION = 'https://appname.azurewbsites.net';

const ENDPOINTS = 
{
    GET_ALL_ROBOTS: 'getAllRobots',
    GET_POST_BY_ID: 'get-post-by-id',
    CREATE_POST: 'create-post',
    UPDATE_POSTS: 'update-post',
    DELETE_POST_BY_ID: 'delete-post-by-id'
};

const development = 
{
    API_URL_GET_ALL_ROBOTS: `${API_BASE_URL_DEVELOPEMENT}/${ENDPOINTS.GET_ALL_ROBOTS}`,
    API_URL_GET_POST_BY_ID: `${API_BASE_URL_DEVELOPEMENT}/${ENDPOINTS.GET_POST_BY_ID}`,
    API_URL_CREATE_POST: `${API_BASE_URL_DEVELOPEMENT}/${ENDPOINTS.CREATE_POST}`,
    API_URL_UPDATE_POST: `${API_BASE_URL_DEVELOPEMENT}/${ENDPOINTS.UPDATE_POST}`,
    API_URL_DELETE_POST_BY_ID: `${API_BASE_URL_DEVELOPEMENT}/${ENDPOINTS.DELETE_POST_BY_ID}`
}
const production = 
{
    API_URL_GET_ALL_POSTS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_POSTS}`,
    API_URL_GET_POST_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_POST_BY_ID}`,
    API_URL_CREATE_POST: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_POST}`,
    API_URL_UPDATE_POST: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_POST}`,
    API_URL_DELETE_POST_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_POST_BY_ID}`
}

const Constants = process.env.NODE_ENV === 'development' ? development: production;

export default Constants;
